name: Update README with recent activity
on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: Readme-Workflows/recent-activity@v2.4.1
        with:
          CONFIG_FILE: .github/recent-activity.config.yml
